export const Constants = {
    public: {
        Enums: {
            asset_extract_status: [
                "pending",
                "extracting",
                "ready",
                "low_confidence",
                "failed",
            ],
            audit_status: [
                "draft",
                "queued",
                "validating",
                "extracting",
                "retrieving",
                "analyzing",
                "validating_result",
                "completed",
                "needs_attention",
                "cancelled",
                "failed",
            ],
            contact_status: [
                "not_contacted",
                "contacting",
                "cooperated",
                "unreachable",
            ],
            creator_decision_status: ["pending", "selected", "discarded"],
            knowledge_base_scope: ["public_law", "private"],
            knowledge_base_status: [
                "empty",
                "processing",
                "ready",
                "needs_attention",
                "failed",
            ],
            knowledge_document_status: [
                "uploaded",
                "parsing",
                "chunking",
                "embedding",
                "validating",
                "ready",
                "needs_attention",
                "cancelled",
                "failed",
            ],
            platform_connection_status: [
                "disconnected",
                "qr_pending",
                "qr_scanned",
                "connected",
                "expired",
                "restricted",
                "failed",
            ],
            platform_kind: ["xiaohongshu", "douyin"],
            project_status: ["active", "archived"],
            risk_level: ["low", "medium", "high", "needs_confirmation"],
            search_partial_reason: [
                "source_exhausted",
                "session_expired",
                "platform_rate_limited",
                "platform_restricted",
                "user_cancelled",
                "upstream_error",
                "execution_timeout",
            ],
            search_task_status: [
                "queued",
                "validating_session",
                "collecting",
                "hard_filtering",
                "analyzing",
                "persisting",
                "completed",
                "partial",
                "cancelled",
                "session_expired",
                "rate_limited",
                "failed",
            ],
        },
    },
};
