import { apiRequest } from "./api-client";
import type { Creator, CreatorPlatform, CreatorStatus } from "../types";

export const DEFAULT_PROJECT_NAME = "玻尿酸新品素人招募";
export const ALL_PROJECTS_SCOPE = "__all__";

export interface ProjectRow { id: string; name: string; product_name?: string | null; description?: string | null; status?: "active" | "archived"; created_at?: string; updated_at?: string; }
export async function listProjects(accessToken: string): Promise<ProjectRow[]> { const response = await apiRequest<{ data: ProjectRow[] }>("/projects", accessToken); return response.data; }
export async function createProject(accessToken: string, input: { name: string; product_name: string; description?: string }): Promise<ProjectRow> { const response = await apiRequest<{ data: ProjectRow }>("/projects", accessToken, { method: "POST", body: JSON.stringify(input) }); return response.data; }
export async function updateProject(accessToken: string, projectId: string, patch: Partial<{ name: string; product_name: string; description: string; status: "active" | "archived" }>): Promise<ProjectRow> { const response = await apiRequest<{ data: ProjectRow }>(`/projects/${projectId}`, accessToken, { method: "PATCH", body: JSON.stringify(patch) }); return response.data; }

export interface ProjectCreatorRow {
  id: string; decision_status: string; contact_status: string; followers: number | null; activity_score: number | null; match_score: number | null; evidence_summary: string; created_at: string; updated_at: string; captured_at: string | null;
  creators: { platform: CreatorPlatform; nickname: string; handle: string | null; profile_url: string | null; avatar_url: string | null; platform_creator_id: string; latest_snapshot: Record<string, unknown> | null } | null;
}
function canonicalProfileUrl(profileUrl: string | null | undefined, platformCreatorId?: string | null): string | undefined { const source = profileUrl ?? platformCreatorId ?? ""; try { const parsed = new URL(source, "https://www.xiaohongshu.com"); const match = parsed.pathname.match(/\/user\/profile\/([^/?#]+)/i); if (match?.[1]) return `https://www.xiaohongshu.com/user/profile/${match[1]}`; } catch { /* fallback below */ } const rawId = source.split(/[?#]/, 1)[0].split("/").filter(Boolean).pop(); return rawId ? `https://www.xiaohongshu.com/user/profile/${rawId}` : undefined; }
export function mapProjectCreator(row: ProjectCreatorRow): Creator { return { id: row.id, platform: "xiaohongshu", name: row.creators?.nickname ?? "未知达人", handle: row.creators?.handle ?? (row.creators?.platform_creator_id ?? "").slice(0, 8), followers: row.followers ?? 0, activity: row.activity_score ?? 0, match: row.match_score ?? 0, tags: [], evidence: row.evidence_summary ?? "", status: (row.decision_status ?? "pending") as CreatorStatus, group: "", contact: row.contact_status ?? "not_contacted", updatedAt: row.updated_at ?? "", firstSearchAt: row.created_at ?? "", profileUrl: canonicalProfileUrl(row.creators?.profile_url, row.creators?.platform_creator_id), avatar: row.creators?.avatar_url ?? undefined }; }
function creatorIdentityKey(creator: Creator): string { const handle = creator.handle.trim().toLowerCase(); if (handle) return `xiaohongshu:handle:${handle}`; if (creator.profileUrl) { try { const path = new URL(creator.profileUrl).pathname.replace(/\/$/, ""); if (path) return `xiaohongshu:profile:${path.toLowerCase()}`; } catch { /* fallback */ } } return `row:${creator.id}`; }
export function dedupeCreators(creators: Creator[]): Creator[] { const merged = new Map<string, Creator>(); for (const creator of creators) { const key = creatorIdentityKey(creator); const existing = merged.get(key); if (!existing) { merged.set(key, creator); continue; } const existingTime = Date.parse(existing.updatedAt || "") || 0; const nextTime = Date.parse(creator.updatedAt || "") || 0; const preferred = nextTime >= existingTime ? creator : existing; const times = [existing.firstSearchAt, creator.firstSearchAt].filter(Boolean).map((value) => Date.parse(value as string)).filter(Number.isFinite); const firstSearchAt = times.length ? new Date(Math.min(...times)).toISOString() : preferred.firstSearchAt; const status = existing.status !== "pending" && preferred.status === "pending" ? existing.status : preferred.status; merged.set(key, { ...preferred, firstSearchAt, status }); } return [...merged.values()]; }
export async function ensureDefaultProject(accessToken: string): Promise<{ id: string; name: string }> { const list = await listProjects(accessToken); const preferredId = window.localStorage.getItem("adproof.activeProjectId"); const existing = list.find((p) => p.id === preferredId && p.status !== "archived") ?? list.find((p) => p.name === DEFAULT_PROJECT_NAME && p.status !== "archived") ?? list.find((p) => p.status !== "archived"); if (existing) return { id: existing.id, name: existing.name }; const created = await createProject(accessToken, { name: DEFAULT_PROJECT_NAME, product_name: "玻尿酸" }); window.localStorage.setItem("adproof.activeProjectId", created.id); return { id: created.id, name: created.name }; }
export async function loadProjectCreators(accessToken: string, projectId: string, status?: CreatorStatus): Promise<Creator[]> { const suffix = status ? `?status=${status}` : ""; const response = await apiRequest<{ data: ProjectCreatorRow[] }>(`/projects/${projectId}/creators${suffix}`, accessToken); return dedupeCreators(response.data.map(mapProjectCreator)); }
export async function loadCreatorsForProjects(accessToken: string, projectIds: string[], status?: CreatorStatus): Promise<Creator[]> { if (!projectIds.length) return []; const rows = await Promise.all(projectIds.map((projectId) => loadProjectCreators(accessToken, projectId, status))); return dedupeCreators(rows.flat()); }
export async function updateProjectCreator(accessToken: string, projectCreatorId: string, patch: Partial<{ decision_status: CreatorStatus; group_id: string | null; contact_status: string; discard_reason: string | null }>): Promise<void> { await apiRequest<void>(`/project-creators/${projectCreatorId}`, accessToken, { method: "PATCH", body: JSON.stringify(patch) }); }
export async function exportProjectCreatorsXlsx(accessToken: string, projectId: string, fileName: string, status?: CreatorStatus): Promise<void> { const suffix = status ? `?status=${status}` : ""; const response = await fetch(`/api/v1/projects/${projectId}/creators/export.xlsx${suffix}`, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) throw new Error(`导出失败（${response.status}）`); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${fileName}.xlsx`; link.click(); URL.revokeObjectURL(url); }
