import type { FastifyPluginAsync } from "fastify";
import type { SupabaseClient } from "@supabase/supabase-js";
import type pg from "pg";
import { z } from "zod";
import { ApiError } from "../errors.js";
import { extractSearchKeyword, parseSearchRuleHeuristic } from "../services/rule-parser.js";
import { cancelSearchTask, createSearchTask, getSearchTask } from "../services/creator-search-service.js";
import { enforceRequestLimit, fingerprint, validateInput } from "../services/input-guard.js";
const createSchema = z.object({ query_text: z.string().trim().min(3).max(2000), confirmed_rule: z.record(z.string(), z.unknown()), target_count: z.number().int().min(1).max(20).optional(), platforms: z.array(z.literal("xiaohongshu")).min(1).max(1).default(["xiaohongshu"]) }).strict();
const parseSchema = z.object({ query_text: z.string().trim().min(3).max(2000) }).strict();
function userId(request: import("fastify").FastifyRequest): string { if (!request.auth) throw new ApiError(401, "AUTH_REQUIRED", "请先登录", false); return request.auth.userId; }
async function ownsProject(client: SupabaseClient, uid: string, projectId: string): Promise<void> { const { data, error } = await client.from("projects").select("id,status").eq("id", projectId).eq("user_id", uid).maybeSingle(); if (error) throw new ApiError(500, "PROJECT_QUERY_FAILED", "查询项目失败", true); if (!data) throw new ApiError(404, "PROJECT_NOT_FOUND", "项目不存在或无权访问", false); if (data.status === "archived") throw new ApiError(409, "PROJECT_ARCHIVED", "已归档项目不可发起检索", false); }
export const searchRoutes: FastifyPluginAsync<{ client: SupabaseClient; pool: pg.Pool }> = async (app, options) => {
  app.post("/projects/:projectId/search-rules:parse", { preHandler: app.requireAuth }, async (request) => { const parsed = parseSchema.safeParse(request.body); if (!parsed.success) throw new ApiError(400, "VALIDATION_INVALID_REQUEST", "检索条件格式不正确", false); const uid = userId(request); const projectId = (request.params as Record<string, string>).projectId; await ownsProject(options.client, uid, projectId); const rule = parseSearchRuleHeuristic(parsed.data.query_text); const guard = validateInput(parsed.data.query_text, "creator"); if (!guard.ok) throw new ApiError(422, guard.code, guard.message, false, { matchedTerms: guard.matchedTerms, confidence: guard.confidence }); const limit = enforceRequestLimit("creator-parse", uid, fingerprint([projectId, parsed.data.query_text]), { max: 20, windowMs: 60000, duplicateWindowMs: 3000 }); if (!limit.ok) throw new ApiError(limit.code === "DUPLICATE_REQUEST" ? 409 : 429, limit.code, limit.message, true, { retryAfterSeconds: limit.retryAfterSeconds }); return { data: rule, meta: { request_id: request.id, inputGuard: { confidence: guard.confidence, matchedTerms: guard.matchedTerms } } }; });
  app.post("/projects/:projectId/search-tasks", { preHandler: app.requireAuth }, async (request) => { const parsed = createSchema.safeParse(request.body); if (!parsed.success) throw new ApiError(400, "VALIDATION_INVALID_REQUEST", "检索任务参数不正确", false, { fields: parsed.error.issues.map((issue) => issue.path.join(".")) }); const uid = userId(request); const projectId = (request.params as Record<string, string>).projectId; await ownsProject(options.client, uid, projectId); const rule = parsed.data.confirmed_rule; const guard = validateInput(parsed.data.query_text, "creator"); if (!guard.ok) throw new ApiError(422, guard.code, guard.message, false, { matchedTerms: guard.matchedTerms, confidence: guard.confidence }); const limit = enforceRequestLimit("creator-search", uid, fingerprint([projectId, parsed.data.query_text, JSON.stringify(rule)]), { max: 5, windowMs: 60000, duplicateWindowMs: 3000 }); if (!limit.ok) throw new ApiError(limit.code === "DUPLICATE_REQUEST" ? 409 : 429, limit.code, limit.message, true, { retryAfterSeconds: limit.retryAfterSeconds }); const keyword = extractSearchKeyword(parsed.data.query_text, rule as never); const result = await createSearchTask(options.client, options.pool, { userId: uid, projectId, queryText: parsed.data.query_text, confirmedRule: rule, targetCount: parsed.data.target_count ?? 20, keyword, platforms: ["xiaohongshu"] }); const task = await getSearchTask(options.client, result.searchTaskId); return { data: task, meta: { request_id: request.id, job_id: result.jobId, inputGuard: { confidence: guard.confidence, matchedTerms: guard.matchedTerms } } }; });
  app.get("/projects/:projectId/search-tasks", { preHandler: app.requireAuth }, async (request) => { const uid = userId(request); const projectId = (request.params as Record<string, string>).projectId; await ownsProject(options.client, uid, projectId); const { data, error } = await options.client.from("search_tasks").select("*").eq("project_id", projectId).eq("user_id", uid).order("created_at", { ascending: false }).limit(50); if (error) throw new ApiError(500, "SEARCH_TASK_QUERY_FAILED", "查询检索任务失败", true); return { data, meta: { request_id: request.id } }; });
  app.get("/search-tasks/:searchTaskId", { preHandler: app.requireAuth }, async (request) => { const uid = userId(request); const task = await getSearchTask(options.client, (request.params as Record<string, string>).searchTaskId); if (!task || task.user_id !== uid) throw new ApiError(404, "SEARCH_TASK_NOT_FOUND", "检索任务不存在或无权访问", false); return { data: task, meta: { request_id: request.id } }; });
  app.post("/search-tasks/:searchTaskId/continue", { preHandler: app.requireAuth }, async (request) => { const uid = userId(request); const previous = await getSearchTask(options.client, (request.params as Record<string, string>).searchTaskId); if (!previous || previous.user_id !== uid) throw new ApiError(404, "SEARCH_TASK_NOT_FOUND", "检索任务不存在或无权访问", false); if (!previous.terminal) throw new ApiError(409, "SEARCH_TASK_ACTIVE", "当前检索仍在进行", false); if (!previous.can_continue) throw new ApiError(409, "SEARCH_SOURCE_EXHAUSTED", "当前条件已无更多可继续检索的数据", false); await ownsProject(options.client, uid, previous.project_id); const keyword = extractSearchKeyword(previous.query_text, previous.confirmed_rule as never); const result = await createSearchTask(options.client, options.pool, { userId: uid, projectId: previous.project_id, queryText: previous.query_text, confirmedRule: previous.confirmed_rule, targetCount: 20, keyword, platforms: ["xiaohongshu"] }); const task = await getSearchTask(options.client, result.searchTaskId); return { data: task, meta: { request_id: request.id, job_id: result.jobId, continued_from: previous.id } }; });
  app.post("/search-tasks/:searchTaskId/cancel", { preHandler: app.requireAuth }, async (request) => { const uid = userId(request); const task = await getSearchTask(options.client, (request.params as Record<string, string>).searchTaskId); if (!task || task.user_id !== uid) throw new ApiError(404, "SEARCH_TASK_NOT_FOUND", "检索任务不存在或无权访问", false); if (task.terminal) throw new ApiError(409, "SEARCH_TASK_TERMINAL", "任务已结束，无法取消", false); await cancelSearchTask(options.client, options.pool, task.id, task.task_id); return { data: { id: task.id, status: "cancelled" }, meta: { request_id: request.id } }; });
};
