import { ArrowDownUp, ArrowUpRight, Check, ChevronDown, ChevronUp, Download, RotateCcw, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { Creator, CreatorStatus } from "../types";
import { exportProjectCreatorsXlsx } from "../lib/project-api";
import { Badge, Button, EmptyState } from "./ui";

const statusLabel: Record<CreatorStatus, string> = { pending: "待处理", selected: "已选入", discarded: "已弃用" };
type SortKey = "name" | "followers" | "activity" | "match" | "firstSearchAt" | "status";
type SortDirection = "asc" | "desc";
function formatSearchTime(value?: string): string { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
function SortableHeading({ label, sortKey, sort, onSort }: { label: string; sortKey: SortKey; sort: { key: SortKey; direction: SortDirection }; onSort: (key: SortKey) => void }) { const active = sort.key === sortKey; return <button type="button" className={`sortable-heading ${active ? "is-active" : ""}`} onClick={() => onSort(sortKey)} aria-label={`按${label}排序`}>{label}{active ? (sort.direction === "desc" ? <ChevronDown size={14} /> : <ChevronUp size={14} />) : <ArrowDownUp size={13} />}</button>; }
export function CreatorTable({ creators, onStatusChange, compact = false }: { creators: Creator[]; onStatusChange: (id: string, status: CreatorStatus) => void; compact?: boolean }) {
  const [sort, setSort] = useState<{ key: SortKey; direction: SortDirection }>({ key: "match", direction: "desc" });
  const sortedCreators = useMemo(() => [...creators].sort((left, right) => { const value = (item: Creator): string | number => sort.key === "name" ? item.name : sort.key === "status" ? statusLabel[item.status] : sort.key === "firstSearchAt" ? item.firstSearchAt ?? "" : item[sort.key]; const a = value(left); const b = value(right); const result = typeof a === "string" || typeof b === "string" ? new Intl.Collator("zh-CN").compare(String(a), String(b)) : Number(a) - Number(b); return sort.direction === "asc" ? result : -result; }), [creators, sort]);
  const onSort = (key: SortKey) => setSort((current) => current.key === key ? { key, direction: current.direction === "asc" ? "desc" : "asc" } : { key, direction: "desc" });
  if (!creators.length) return <EmptyState title="暂无符合条件的达人" description="调整筛选条件，或开始一次新的达人检索。" />;
  return <div className="table-wrap"><table className="data-table creator-table"><thead><tr><th><SortableHeading label="达人" sortKey="name" sort={sort} onSort={onSort} /></th><th>数据来源</th><th><SortableHeading label="粉丝" sortKey="followers" sort={sort} onSort={onSort} /></th><th><SortableHeading label="活跃度" sortKey="activity" sort={sort} onSort={onSort} /></th><th><SortableHeading label="匹配分" sortKey="match" sort={sort} onSort={onSort} /></th>{!compact && <th><SortableHeading label="首次检索时间" sortKey="firstSearchAt" sort={sort} onSort={onSort} /></th>}<th>证据标签</th><th><SortableHeading label="状态" sortKey="status" sort={sort} onSort={onSort} /></th><th>操作</th></tr></thead><tbody>{sortedCreators.map((creator) => <tr key={creator.id}><td><div className="creator-cell"><div className="avatar">{creator.avatar ? <img src={creator.avatar} alt="" /> : creator.name.slice(0, 1)}</div><div><strong>{creator.name}</strong><span>{creator.handle}</span></div></div></td><td><Badge tone="brand">小红书</Badge></td><td>{creator.followers.toLocaleString()}</td><td><span className="metric-score">{creator.activity}</span></td><td><strong className="match-score">{creator.match}</strong></td>{!compact && <td className="first-search-time">{formatSearchTime(creator.firstSearchAt)}</td>}<td><div className="tag-list">{creator.tags.slice(0, compact ? 1 : 2).map((tag) => <Badge key={tag} tone="brand">{tag}</Badge>)}</div>{!compact && <span className="evidence-line" title={creator.evidence}>{creator.evidence}</span>}</td><td><Badge tone={creator.status === "selected" ? "success" : creator.status === "discarded" ? "danger" : "neutral"}>{statusLabel[creator.status]}</Badge></td><td><div className="row-actions"><a href={creator.profileUrl ?? `https://www.xiaohongshu.com/user/profile/${creator.id}`} target="_blank" rel="noreferrer" aria-label="打开达人主页" title="打开达人主页"><ArrowUpRight size={16} /></a>{creator.status !== "selected" && <button onClick={() => onStatusChange(creator.id, "selected")} title="选入达人" aria-label="选入达人"><Check size={16} /></button>}{creator.status !== "discarded" && <button onClick={() => onStatusChange(creator.id, "discarded")} title="弃用达人" aria-label="弃用达人"><X size={16} /></button>}{creator.status !== "pending" && <button onClick={() => onStatusChange(creator.id, "pending")} title="恢复待处理" aria-label="恢复待处理"><RotateCcw size={15} /></button>}</div></td></tr>)}</tbody></table></div>;
}
export function CreatorExportButton({ accessToken, projectId, fileName, status, disabled = false, className = "" }: { accessToken: string; projectId: string; fileName: string; status?: CreatorStatus; disabled?: boolean; className?: string }) { const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const exportFile = async () => { setBusy(true); setError(null); try { await exportProjectCreatorsXlsx(accessToken, projectId, fileName, status); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "导出失败，请重试"); } finally { setBusy(false); } }; return <div className={`export-action ${className}`}><Button tone="secondary" className="creator-export-button" icon={<Download size={16} />} loading={busy} disabled={disabled} onClick={() => void exportFile()}>导出 Excel</Button>{error && <span className="form-message form-message--error">{error}</span>}</div>; }
