import { randomUUID } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type pg from "pg";
import { ApiError } from "../errors.js";
export interface CreateSearchTaskInput { userId: string; projectId: string; queryText: string; confirmedRule: Record<string, unknown>; targetCount: number; keyword: string; platforms: Array<"xiaohongshu">; }
export interface SearchTaskEventRow { seq: number; status: string; stage: string; terminal: boolean; progress: number; message_code: string; error_code: string | null; occurred_at: string; }
export interface SearchTaskView { id: string; task_id: string; user_id: string; project_id: string; query_text: string; confirmed_rule: Record<string, unknown>; target_count: number; status: string; progress: number; terminal: boolean; can_continue: boolean; collected_count: number; persisted_count: number; duplicate_count: number; stage_counts: Record<string, number>; loop_state: Record<string, unknown>; partial_reason: string | null; message_code: string | null; error_code: string | null; error_message: string | null; model_version: string | null; prompt_version: string | null; created_at: string; updated_at: string; }
function mapTaskRow(row: Record<string, unknown>): SearchTaskView { return { id: row.id as string, task_id: row.task_id as string, user_id: row.user_id as string, project_id: row.project_id as string, query_text: row.query_text as string, confirmed_rule: row.confirmed_rule && typeof row.confirmed_rule === "object" ? row.confirmed_rule as Record<string, unknown> : {}, target_count: Number(row.target_count ?? 20), status: row.status as string, progress: row.progress as number, terminal: row.terminal as boolean, can_continue: Boolean(row.can_continue), collected_count: row.collected_count as number, persisted_count: row.persisted_count as number, duplicate_count: row.duplicate_count as number, stage_counts: row.stage_counts && typeof row.stage_counts === "object" ? row.stage_counts as Record<string, number> : {}, loop_state: row.loop_state && typeof row.loop_state === "object" ? row.loop_state as Record<string, unknown> : {}, partial_reason: row.partial_reason as string | null, message_code: row.message_code as string | null, error_code: row.error_code as string | null, error_message: row.error_message as string | null, model_version: row.model_version as string | null, prompt_version: row.prompt_version as string | null, created_at: row.created_at as string, updated_at: row.updated_at as string }; }
export async function createSearchTask(client: SupabaseClient, pool: pg.Pool, input: CreateSearchTaskInput): Promise<{ searchTaskId: string; jobId: string }> { const { data: activeTasks, error: activeError } = await client.from("search_tasks").select("id,task_id,status").eq("user_id", input.userId).in("status", ["queued", "validating_session", "collecting", "hard_filtering", "analyzing", "persisting"]); if (activeError) throw new Error(`query active tasks failed: ${activeError.message}`); if ((activeTasks ?? []).length > 0) throw new ApiError(409, "SEARCH_TASK_ACTIVE", "已有达人检索任务正在执行，请等待本批完成后再开始下一批。", false, { searchTaskId: String(activeTasks?.[0]?.id ?? "") }); const searchTaskId = randomUUID(); const jobId = randomUUID(); const idempotencyKey = randomUUID(); await pool.query(`insert into private.jobs (id, user_id, type, status, stage, payload, idempotency_scope, idempotency_key, run_after) values ($1, $2, 'creator_search', 'queued', 'queued', $3, 'creator_search', $4, now())`, [jobId, input.userId, { search_task_id: searchTaskId, project_id: input.projectId, keyword: input.keyword, query_text: input.queryText, target_count: input.targetCount, confirmed_rule: input.confirmedRule, platforms: ["xiaohongshu"] }, idempotencyKey]); const { error: taskError } = await client.from("search_tasks").insert({ id: searchTaskId, task_id: jobId, user_id: input.userId, project_id: input.projectId, idempotency_key: idempotencyKey, query_text: input.queryText, confirmed_rule: input.confirmedRule, target_count: input.targetCount }); if (taskError) { await pool.query("delete from private.jobs where id = $1", [jobId]).catch(() => undefined); throw new Error(`create search_task failed: ${taskError.message}`); } return { searchTaskId, jobId }; }
export async function getSearchTask(client: SupabaseClient, searchTaskId: string): Promise<SearchTaskView | null> { const { data, error } = await client.from("search_tasks").select("*").eq("id", searchTaskId).maybeSingle(); if (error) throw new ApiError(500, "SEARCH_TASK_QUERY_FAILED", "查询检索任务失败", true); return data ? mapTaskRow(data as unknown as Record<string, unknown>) : null; }
export async function listJobEvents(pool: pg.Pool, jobId: string, afterSeq = 0): Promise<SearchTaskEventRow[]> { const result = await pool.query(`select seq, status, stage, terminal, progress, message_code, error_code, occurred_at from private.job_events where job_id = $1 and seq > $2 order by seq asc`, [jobId, afterSeq]); return result.rows.map((row) => ({ seq: row.seq as number, status: row.status as string, stage: row.stage as string, terminal: row.terminal as boolean, progress: row.progress as number, message_code: row.message_code as string, error_code: row.error_code as string | null, occurred_at: (row.occurred_at as Date).toISOString() })); }
export async function cancelSearchTask(client: SupabaseClient, pool: pg.Pool, searchTaskId: string, jobId: string): Promise<void> { await pool.query(`update private.jobs set cancel_requested = true, updated_at = now() where id = $1 and status in ('queued', 'running')`, [jobId]); await client.from("search_tasks").update({ status: "cancelled", terminal: true, message_code: "SEARCH_CANCELLED" }).eq("id", searchTaskId).eq("terminal", false); }
