/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户资料 */
        get: operations["getCurrentProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新当前用户资料 */
        patch: operations["updateCurrentProfile"];
        trace?: never;
    };
    "/platform-connections/xiaohongshu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前小红书连接状态 */
        get: operations["getXiaohongshuConnection"];
        put?: never;
        /**
         * 创建或刷新小红书扫码连接
         * @description 创建短时二维码会话。响应不包含 Cookie、Token 或浏览器 Storage State。
         */
        post: operations["createXiaohongshuConnection"];
        /** 断开并删除小红书会话 */
        delete: operations["disconnectXiaohongshu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 创建推广项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目详情和统计 */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * 归档项目
         * @description MVP 不物理删除项目及候选历史，只将项目标记为 archived。
         */
        delete: operations["archiveProject"];
        options?: never;
        head?: never;
        /** 更新项目 */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目自定义分组 */
        get: operations["listProjectGroups"];
        put?: never;
        /** 创建项目分组 */
        post: operations["createProjectGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除空分组
         * @description 分组内仍有达人时返回 GROUP_NOT_EMPTY，不自动移动达人。
         */
        delete: operations["deleteProjectGroup"];
        options?: never;
        head?: never;
        /** 重命名项目分组 */
        patch: operations["updateProjectGroup"];
        trace?: never;
    };
    "/projects/{projectId}/search-rules:parse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 将自然语言解析为待确认筛选规则
         * @description 此接口只解析规则，不启动真实小红书检索。
         */
        post: operations["parseSearchRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/search-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目检索任务历史 */
        get: operations["listProjectSearchTasks"];
        put?: never;
        /**
         * 确认规则并创建真实达人检索任务
         * @description 默认目标返回 50 人。服务端自动排除当前项目已有的小红书用户 ID；
         *     未连接、会话过期或存在同类运行任务时返回明确错误。
         */
        post: operations["createSearchTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-tasks/{searchTaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchTaskId: components["parameters"]["SearchTaskId"];
            };
            cookie?: never;
        };
        /** 获取检索任务详情与进度 */
        get: operations["getSearchTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-tasks/{searchTaskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchTaskId: components["parameters"]["SearchTaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 请求取消检索任务 */
        post: operations["cancelSearchTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/creators": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目达人列表 */
        get: operations["listProjectCreators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-creators/{projectCreatorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectCreatorId: components["parameters"]["ProjectCreatorId"];
            };
            cookie?: never;
        };
        /** 获取项目达人详情和证据 */
        get: operations["getProjectCreator"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新达人决策状态、分组、标签或联系状态 */
        patch: operations["updateProjectCreator"];
        trace?: never;
    };
    "/projects/{projectId}/creators:bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量更新达人状态或分组 */
        post: operations["bulkUpdateProjectCreators"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/creators/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 导出项目达人 Excel */
        get: operations["exportProjectCreators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取公共广告法库和当前用户私有知识库 */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 创建私有知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{knowledgeBaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        /** 获取知识库详情 */
        get: operations["getKnowledgeBase"];
        put?: never;
        post?: never;
        /**
         * 删除私有知识库及其文档
         * @description 公共广告法知识库不可删除；历史审核保留当时的规则版本快照。
         */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        /**
         * 更新私有知识库名称
         * @description 公共广告法知识库不可通过此接口修改。
         */
        patch: operations["updateKnowledgeBase"];
        trace?: never;
    };
    "/knowledge-bases/{knowledgeBaseId}/document-upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建知识库文档签名上传凭证 */
        post: operations["createKnowledgeDocumentUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{knowledgeBaseId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        /** 获取知识库文档列表 */
        get: operations["listKnowledgeDocuments"];
        put?: never;
        /** 确认上传完成并创建解析任务 */
        post: operations["commitKnowledgeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** 获取文档解析状态 */
        get: operations["getKnowledgeDocument"];
        put?: never;
        post?: never;
        /** 删除私有知识库文档 */
        delete: operations["deleteKnowledgeDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-asset-upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建审核图片签名上传凭证 */
        post: operations["createAuditAssetUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户审核记录 */
        get: operations["listAuditTasks"];
        put?: never;
        /** 创建图文审核草稿 */
        post: operations["createAuditTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-tasks/{auditTaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        /** 获取审核任务、结果和版本快照 */
        get: operations["getAuditTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新审核草稿
         * @description 只有 draft 状态允许修改。
         */
        patch: operations["updateAuditDraft"];
        trace?: never;
    };
    "/audit-tasks/{auditTaskId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交图文审核任务
         * @description 公共广告法库固定启用；私有知识库按草稿中选择的版本生成快照。
         */
        post: operations["submitAuditTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-tasks/{auditTaskId}/reruns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 复制历史输入并创建新的审核草稿
         * @description 不覆盖原审核结果；新草稿可重新选择当前可用知识库。
         */
        post: operations["rerunAuditTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** 获取通用异步任务状态 */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 请求取消可取消的异步任务
         * @description 检索、知识库解析和内容审核在进入不可中断提交阶段前允许取消；不支持取消时返回 TASK_NOT_CANCELLABLE。
         */
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/events": {
        parameters: {
            query?: {
                /** @description 从该事件序号之后开始发送，用于断线续传 */
                after_seq?: number;
            };
            header?: {
                /** @description 与 after_seq 等价；两者同时出现时取更大的有效序号 */
                "Last-Event-ID"?: number;
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /**
         * 订阅异步任务事件
         * @description SSE 事件名为 task.progress、task.status 或 task.error；data 为 TaskEvent JSON。
         *     服务端最长每 15 秒发送一次 `: heartbeat` 注释帧。浏览器也可发送 Last-Event-ID；
         *     客户端 30 秒未收到事件或心跳时主动中止并重连。SSE 不可用时轮询 GET /tasks/{taskId}。
         */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /** Format: uuid */
            request_id: string;
            next_cursor?: string | null;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                retryable: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
            meta: components["schemas"]["Meta"];
        };
        HealthResponse: {
            data: {
                /** @constant */
                status: "ok";
                version: string;
                /** Format: date-time */
                time: string;
            };
            meta: components["schemas"]["Meta"];
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProfileResponse: {
            data: components["schemas"]["UserProfile"];
            meta: components["schemas"]["Meta"];
        };
        UpdateProfileRequest: {
            display_name?: string;
        };
        /** @enum {string} */
        PlatformConnectionStatus: "disconnected" | "qr_pending" | "qr_scanned" | "connected" | "expired" | "restricted" | "failed";
        PlatformConnection: {
            /** Format: uuid */
            id: string | null;
            /** Format: uuid */
            task_id: string | null;
            /** @constant */
            platform: "xiaohongshu";
            status: components["schemas"]["PlatformConnectionStatus"];
            /** Format: uri */
            qr_image_url?: string | null;
            /** Format: date-time */
            qr_expires_at?: string | null;
            /** Format: date-time */
            session_expires_at?: string | null;
            /** Format: date-time */
            last_verified_at?: string | null;
            account_display_name?: string | null;
            account_handle_masked?: string | null;
            message_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlatformConnectionResponse: {
            data: components["schemas"]["PlatformConnection"];
            meta: components["schemas"]["Meta"];
        };
        CreatedPlatformConnection: components["schemas"]["PlatformConnection"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
        };
        CreatedPlatformConnectionResponse: {
            data: components["schemas"]["CreatedPlatformConnection"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        ProjectStatus: "active" | "archived";
        ProjectStats: {
            pending: number;
            selected: number;
            discarded: number;
            total: number;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            product_name: string;
            description?: string | null;
            status: components["schemas"]["ProjectStatus"];
            stats: components["schemas"]["ProjectStats"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateProjectRequest: {
            name: string;
            product_name: string;
            description?: string;
        };
        UpdateProjectRequest: {
            name?: string;
            product_name?: string;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"];
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
            meta: components["schemas"]["Meta"];
        };
        ProjectListResponse: {
            data: components["schemas"]["Project"][];
            meta: components["schemas"]["Meta"];
        };
        Group: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            name: string;
            creator_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateGroupRequest: {
            name: string;
        };
        UpdateGroupRequest: components["schemas"]["CreateGroupRequest"];
        GroupResponse: {
            data: components["schemas"]["Group"];
            meta: components["schemas"]["Meta"];
        };
        GroupListResponse: {
            data: components["schemas"]["Group"][];
            meta: components["schemas"]["Meta"];
        };
        /** @description 单个非负整数比较；区间条件在 search-rule.v1 中必须进入 ambiguities，由用户拆分或确认，不能静默丢弃边界。 */
        NumericComparison: {
            /** @enum {string} */
            operator: "lt" | "lte" | "eq" | "gte" | "gt";
            value: number;
        };
        SemanticCondition: {
            id: string;
            /** @enum {string} */
            type: "experience" | "concern" | "content_topic" | "persona" | "custom";
            terms: string[];
            /** @enum {string} */
            match: "any" | "all" | "none";
        };
        RankingRule: {
            /** @enum {string} */
            field: "activity" | "followers" | "match_score" | "recent_post_at";
            /** @enum {string} */
            direction: "asc" | "desc";
        };
        ParsedSearchRule: {
            hard_filters: {
                followers?: components["schemas"]["NumericComparison"];
                posts_last_30d?: components["schemas"]["NumericComparison"];
                days_since_last_post?: components["schemas"]["NumericComparison"];
            };
            semantic_conditions: components["schemas"]["SemanticCondition"][];
            ranking: components["schemas"]["RankingRule"][];
            /** @default 50 */
            limit: number;
            ambiguities: string[];
            /** @constant */
            schema_version: "search-rule.v1";
        };
        ParseSearchRuleRequest: {
            query: string;
            /** @default 50 */
            limit: number;
        };
        ParsedSearchRuleData: {
            query: string;
            parsed_rule: components["schemas"]["ParsedSearchRule"];
            model_version: string;
            prompt_version: string;
        };
        ParsedSearchRuleResponse: {
            data: components["schemas"]["ParsedSearchRuleData"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        SearchTaskStatus: "queued" | "validating_session" | "collecting" | "hard_filtering" | "analyzing" | "persisting" | "completed" | "partial" | "cancelled" | "session_expired" | "rate_limited" | "failed";
        CreateSearchTaskRequest: {
            query: string;
            confirmed_rule: components["schemas"]["ParsedSearchRule"];
            /**
             * @default true
             * @constant
             */
            exclude_existing: true;
        };
        SearchTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
            /** Format: uuid */
            project_id: string;
            query: string;
            confirmed_rule: components["schemas"]["ParsedSearchRule"];
            status: components["schemas"]["SearchTaskStatus"];
            progress: number;
            terminal: boolean;
            target_count: number;
            collected_count: number;
            persisted_count: number;
            duplicate_count: number;
            partial_reason: components["schemas"]["SearchPartialReason"] | null;
            can_continue: boolean;
            retry_after_seconds: number | null;
            message_code?: string | null;
            error_code?: string | null;
            error_message?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        SearchPartialReason: "source_exhausted" | "session_expired" | "platform_rate_limited" | "platform_restricted" | "user_cancelled" | "upstream_error";
        SearchTaskResponse: {
            data: components["schemas"]["SearchTask"];
            meta: components["schemas"]["Meta"];
        };
        SearchTaskListResponse: {
            data: components["schemas"]["SearchTask"][];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        CreatorDecisionStatus: "pending" | "selected" | "discarded";
        /** @enum {string} */
        ContactStatus: "not_contacted" | "contacting" | "cooperated" | "unreachable";
        CreatorEvidence: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            evidence_type: "profile" | "post" | "metric" | "ai_analysis";
            /** Format: uri */
            source_url?: string | null;
            excerpt: string;
            confidence?: number | null;
            /** Format: date-time */
            captured_at: string;
        };
        ProjectCreator: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            platform_creator_id: string;
            nickname: string;
            handle?: string | null;
            /** Format: uri */
            profile_url: string;
            /** Format: uri */
            avatar_url?: string | null;
            followers: number | null;
            posts_last_30d?: number | null;
            median_engagement?: number | null;
            /** Format: date-time */
            last_post_at?: string | null;
            activity_score: number | null;
            match_score: number | null;
            /** @enum {string} */
            data_completeness: "complete" | "partial";
            field_warnings: string[];
            decision_status: components["schemas"]["CreatorDecisionStatus"];
            group?: components["schemas"]["Group"] | null;
            tags: string[];
            contact_status: components["schemas"]["ContactStatus"];
            discard_reason?: string | null;
            evidence_summary: string;
            evidence?: components["schemas"]["CreatorEvidence"][];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateProjectCreatorRequest: {
            decision_status?: components["schemas"]["CreatorDecisionStatus"];
            /** Format: uuid */
            group_id?: string | null;
            tags?: string[];
            contact_status?: components["schemas"]["ContactStatus"];
            discard_reason?: string | null;
        };
        BulkUpdateProjectCreatorsRequest: {
            ids: string[];
            changes: {
                decision_status?: components["schemas"]["CreatorDecisionStatus"];
                /** Format: uuid */
                group_id?: string | null;
            };
        };
        ProjectCreatorResponse: {
            data: components["schemas"]["ProjectCreator"];
            meta: components["schemas"]["Meta"];
        };
        ProjectCreatorListData: {
            items: components["schemas"]["ProjectCreator"][];
            stats: components["schemas"]["ProjectStats"];
        };
        ProjectCreatorListResponse: {
            data: components["schemas"]["ProjectCreatorListData"];
            meta: components["schemas"]["Meta"];
        };
        BulkUpdateResult: {
            updated_count: number;
            failed_ids: string[];
        };
        BulkUpdateProjectCreatorsResponse: {
            data: components["schemas"]["BulkUpdateResult"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        KnowledgeBaseScope: "public_law" | "private";
        /** @enum {string} */
        KnowledgeBaseStatus: "empty" | "processing" | "ready" | "needs_attention" | "failed";
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            scope: components["schemas"]["KnowledgeBaseScope"];
            name: string;
            description?: string | null;
            status: components["schemas"]["KnowledgeBaseStatus"];
            version: number;
            document_count: number;
            ready_document_count: number;
            selectable: boolean;
            /** Format: uri */
            source_url?: string | null;
            /** Format: date */
            effective_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateKnowledgeBaseRequest: {
            name: string;
            description?: string;
        };
        UpdateKnowledgeBaseRequest: {
            name?: string;
            description?: string | null;
        };
        KnowledgeBaseResponse: {
            data: components["schemas"]["KnowledgeBase"];
            meta: components["schemas"]["Meta"];
        };
        KnowledgeBaseListResponse: {
            data: components["schemas"]["KnowledgeBase"][];
            meta: components["schemas"]["Meta"];
        };
        CreateDocumentUploadIntentRequest: {
            file_name: string;
            /** @enum {string} */
            mime_type: "application/pdf" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document" | "text/plain" | "text/markdown";
            size_bytes: number;
            checksum_sha256: string;
        };
        CreateAuditAssetUploadIntentRequest: {
            file_name: string;
            /** @enum {string} */
            mime_type: "image/jpeg" | "image/png";
            size_bytes: number;
            checksum_sha256: string;
        };
        UploadIntent: {
            /** Format: uuid */
            upload_id: string;
            storage_path: string;
            /** @constant */
            method: "PUT";
            /** Format: uri */
            upload_url: string;
            required_headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        UploadIntentResponse: {
            data: components["schemas"]["UploadIntent"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        KnowledgeDocumentStatus: "uploaded" | "parsing" | "chunking" | "embedding" | "validating" | "ready" | "needs_attention" | "cancelled" | "failed";
        CommitKnowledgeDocumentRequest: {
            /** Format: uuid */
            upload_id: string;
            storage_path: string;
            file_name: string;
            /** @enum {string} */
            mime_type: "application/pdf" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document" | "text/plain" | "text/markdown";
            size_bytes: number;
            checksum_sha256: string;
        };
        KnowledgeDocument: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description 私有文档解析任务 ID；平台维护的公共广告法文档为 null。
             */
            task_id: string | null;
            /** Format: uuid */
            knowledge_base_id: string;
            file_name: string;
            mime_type: string;
            size_bytes: number;
            checksum_sha256: string;
            status: components["schemas"]["KnowledgeDocumentStatus"];
            version: number;
            chunk_count?: number | null;
            page_count?: number | null;
            message_code?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        QueuedKnowledgeDocument: components["schemas"]["KnowledgeDocument"] & {
            /** Format: uuid */
            task_id: string;
        };
        KnowledgeDocumentResponse: {
            data: components["schemas"]["KnowledgeDocument"];
            meta: components["schemas"]["Meta"];
        };
        QueuedKnowledgeDocumentResponse: {
            data: components["schemas"]["QueuedKnowledgeDocument"];
            meta: components["schemas"]["Meta"];
        };
        KnowledgeDocumentListResponse: {
            data: components["schemas"]["KnowledgeDocument"][];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        RiskLevel: "low" | "medium" | "high" | "needs_confirmation";
        /** @enum {string} */
        AuditStatus: "draft" | "queued" | "validating" | "extracting" | "retrieving" | "analyzing" | "validating_result" | "completed" | "needs_attention" | "cancelled" | "failed";
        AuditAssetInput: {
            /** Format: uuid */
            upload_id: string;
            storage_path: string;
            file_name: string;
            /** @enum {string} */
            mime_type: "image/jpeg" | "image/png";
            size_bytes: number;
            checksum_sha256: string;
            sort_order: number;
        };
        AuditAsset: {
            /** Format: uuid */
            id: string;
            file_name: string;
            mime_type: string;
            size_bytes: number;
            sort_order: number;
            /** Format: uri */
            preview_url?: string | null;
            /** @enum {string} */
            extract_status: "pending" | "extracting" | "ready" | "low_confidence" | "failed";
            extracted_text?: string | null;
            extraction_confidence?: number | null;
        };
        CreateAuditTaskRequest: {
            task_name?: string | null;
            title: string;
            body: string;
            requirements?: string | null;
            assets: components["schemas"]["AuditAssetInput"][];
            private_knowledge_base_ids: string[];
        };
        UpdateAuditTaskRequest: {
            task_name?: string | null;
            title?: string;
            body?: string;
            requirements?: string | null;
            assets?: components["schemas"]["AuditAssetInput"][];
            private_knowledge_base_ids?: string[];
        };
        KnowledgeSourceSnapshot: {
            /** Format: uuid */
            knowledge_base_id: string;
            scope: components["schemas"]["KnowledgeBaseScope"];
            name: string;
            version: number;
            document_versions: {
                /** Format: uuid */
                document_id: string;
                version: number;
            }[];
        };
        FindingLocation: {
            /** @enum {string} */
            type: "title" | "body" | "image";
            quote: string;
            /** Format: uuid */
            asset_id?: string | null;
            start_offset?: number | null;
            end_offset?: number | null;
        };
        FindingSource: {
            scope: components["schemas"]["KnowledgeBaseScope"];
            /** Format: uuid */
            knowledge_base_id: string;
            knowledge_base_version: number;
            /** Format: uuid */
            document_id: string;
            document_version: number;
            /** Format: uuid */
            chunk_id: string;
            document: string;
            locator: string;
            excerpt: string;
            /** Format: uri */
            source_url?: string | null;
        };
        AuditFinding: {
            /** Format: uuid */
            id: string;
            risk_level: components["schemas"]["RiskLevel"];
            category: string;
            location: components["schemas"]["FindingLocation"];
            source: components["schemas"]["FindingSource"];
            explanation: string;
            suggestion: string;
            confidence: number;
        };
        RiskCounts: {
            high: number;
            medium: number;
            low: number;
            needs_confirmation: number;
        };
        AuditResult: {
            overall_risk: components["schemas"]["RiskLevel"];
            risk_counts: components["schemas"]["RiskCounts"];
            findings: components["schemas"]["AuditFinding"][];
            coverage_warnings: components["schemas"]["CoverageWarning"][];
            recommended_action?: string | null;
            /** @constant */
            disclaimer: "AI辅助审核结果，不构成法律意见，需人工复核。";
            /** @constant */
            schema_version: "content-audit.v1";
        };
        CoverageWarning: {
            /** @enum {string} */
            code: "IMAGE_TEXT_LOW_CONFIDENCE" | "IMAGE_TEXT_EXTRACTION_FAILED" | "INPUT_TRUNCATED" | "KNOWLEDGE_COVERAGE_LIMITED";
            message: string;
            /** Format: uuid */
            asset_id?: string | null;
            location?: string | null;
        };
        AuditTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id?: string | null;
            /** Format: uuid */
            parent_audit_task_id?: string | null;
            task_name: string | null;
            title: string;
            body: string;
            requirements?: string | null;
            assets: components["schemas"]["AuditAsset"][];
            status: components["schemas"]["AuditStatus"];
            /** @default 0 */
            progress: number;
            message_code?: string | null;
            private_knowledge_base_ids: string[];
            knowledge_snapshot?: components["schemas"]["KnowledgeSourceSnapshot"][];
            result?: components["schemas"]["AuditResult"] | null;
            error_code?: string | null;
            error_message?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuditTaskResponse: {
            data: components["schemas"]["AuditTask"];
            meta: components["schemas"]["Meta"];
        };
        SubmittedAuditTask: components["schemas"]["AuditTask"] & {
            /** Format: uuid */
            task_id: string;
        };
        SubmittedAuditTaskResponse: {
            data: components["schemas"]["SubmittedAuditTask"];
            meta: components["schemas"]["Meta"];
        };
        AuditTaskSummary: {
            /** Format: uuid */
            id: string;
            task_name: string | null;
            title: string;
            status: components["schemas"]["AuditStatus"];
            overall_risk: components["schemas"]["RiskLevel"] | null;
            risk_counts: components["schemas"]["RiskCounts"] | null;
            knowledge_base_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at: string | null;
        };
        AuditTaskListResponse: {
            data: components["schemas"]["AuditTaskSummary"][];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        TaskStatus: "queued" | "running" | "completed" | "partial" | "needs_attention" | "cancelled" | "failed";
        /** @enum {string} */
        TaskStage: "queued" | "xhs_qr_pending" | "xhs_qr_scanned" | "xhs_connected" | "validating_session" | "collecting" | "hard_filtering" | "analyzing_creators" | "persisting_creators" | "parsing_document" | "chunking_document" | "embedding_document" | "validating_document" | "validating_audit" | "extracting_assets" | "retrieving_rules" | "analyzing_content" | "validating_result" | "completed" | "partial" | "needs_attention" | "cancelled" | "failed";
        /** @enum {string} */
        TaskMessageCode: "TASK_QUEUED" | "XHS_QR_READY" | "XHS_QR_SCANNED" | "XHS_CONNECTED" | "SEARCH_VALIDATING_SESSION" | "SEARCH_COLLECTING" | "SEARCH_HARD_FILTERING" | "SEARCH_ANALYZING" | "SEARCH_PERSISTING" | "SEARCH_COMPLETED" | "SEARCH_PARTIAL" | "KB_PARSING" | "KB_CHUNKING" | "KB_EMBEDDING" | "KB_VALIDATING" | "KB_READY" | "AUDIT_VALIDATING" | "AUDIT_EXTRACTING" | "AUDIT_RETRIEVING" | "AUDIT_ANALYZING" | "AUDIT_VALIDATING_RESULT" | "AUDIT_COMPLETED" | "TASK_NEEDS_ATTENTION" | "TASK_CANCELLED" | "TASK_FAILED";
        Task: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "xhs_connect" | "creator_search" | "knowledge_ingest" | "content_audit";
            status: components["schemas"]["TaskStatus"];
            stage: components["schemas"]["TaskStage"];
            terminal: boolean;
            progress: number;
            message_code: components["schemas"]["TaskMessageCode"] | null;
            error_code?: string | null;
            retryable: boolean;
            retry_after_seconds: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        TaskResponse: {
            data: components["schemas"]["Task"];
            meta: components["schemas"]["Meta"];
        };
        TaskEvent: {
            seq: number;
            /** Format: uuid */
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            stage: components["schemas"]["TaskStage"];
            terminal: boolean;
            progress: number;
            message_code: components["schemas"]["TaskMessageCode"];
            error_code: string | null;
            retry_after_seconds: number | null;
            data?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurred_at: string;
        };
    };
    responses: {
        /** @description access token 缺失、无效或已过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 当前用户无权执行该操作 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在，或资源不属于当前用户 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求格式、字段或文件声明无效 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源状态、幂等键或并发任务冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求合法但当前业务条件不满足 */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 用户并发、API 或平台访问频率受限 */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
        IdempotencyKey: string;
        Cursor: string;
        PageSize: number;
        ProjectId: string;
        GroupId: string;
        SearchTaskId: string;
        ProjectCreatorId: string;
        KnowledgeBaseId: string;
        DocumentId: string;
        AuditTaskId: string;
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 更新后的资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getXiaohongshuConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前连接状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConnectionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createXiaohongshuConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已创建二维码会话 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPlatformConnectionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    disconnectXiaohongshu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已断开连接 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["ProjectStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 已创建项目 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已归档 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description 更新后的项目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjectGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分组列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description 已创建分组 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description 更新后的分组 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    parseSearchRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseSearchRuleRequest"];
            };
        };
        responses: {
            /** @description 结构化规则和歧义提示 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedSearchRuleResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    listProjectSearchTasks: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 检索任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTaskListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createSearchTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSearchTaskRequest"];
            };
        };
        responses: {
            /** @description 任务已排队 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTaskResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    getSearchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchTaskId: components["parameters"]["SearchTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 检索任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelSearchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                searchTaskId: components["parameters"]["SearchTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接受取消请求 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listProjectCreators: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                decision_status?: components["schemas"]["CreatorDecisionStatus"];
                group_id?: string;
                tag?: string;
                /** @description 按昵称或小红书号搜索 */
                q?: string;
                sort?: "match_score_desc" | "followers_asc" | "activity_desc" | "updated_at_desc";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 达人列表与统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreatorListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectCreator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectCreatorId: components["parameters"]["ProjectCreatorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 达人详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreatorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProjectCreator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectCreatorId: components["parameters"]["ProjectCreatorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectCreatorRequest"];
            };
        };
        responses: {
            /** @description 更新后的项目达人 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreatorResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    bulkUpdateProjectCreators: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateProjectCreatorsRequest"];
            };
        };
        responses: {
            /** @description 批量更新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkUpdateProjectCreatorsResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    exportProjectCreators: {
        parameters: {
            query?: {
                decision_status?: components["schemas"]["CreatorDecisionStatus"];
                group_id?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excel 文件，包含主页链接、采集时间、证据摘要、分组和状态 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 已创建私有知识库 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 更新后的知识库 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createKnowledgeDocumentUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentUploadIntentRequest"];
            };
        };
        responses: {
            /** @description 短时签名上传信息 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listKnowledgeDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    commitKnowledgeDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                knowledgeBaseId: components["parameters"]["KnowledgeBaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitKnowledgeDocumentRequest"];
            };
        };
        responses: {
            /** @description 文档已登记，解析任务已排队 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedKnowledgeDocumentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    getKnowledgeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteKnowledgeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除，知识库生成新版本 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createAuditAssetUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuditAssetUploadIntentRequest"];
            };
        };
        responses: {
            /** @description 短时签名上传信息 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    listAuditTasks: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["AuditStatus"];
                overall_risk?: components["schemas"]["RiskLevel"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审核记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTaskListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAuditTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuditTaskRequest"];
            };
        };
        responses: {
            /** @description 已创建审核草稿 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTaskResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getAuditTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审核任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAuditDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAuditTaskRequest"];
            };
        };
        responses: {
            /** @description 更新后的草稿 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTaskResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitAuditTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同一用户、接口和键返回同一创建结果。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审核任务已排队 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedAuditTaskResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    rerunAuditTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditTaskId: components["parameters"]["AuditTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新审核草稿 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接受取消请求 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: {
                /** @description 从该事件序号之后开始发送，用于断线续传 */
                after_seq?: number;
            };
            header?: {
                /** @description 与 after_seq 等价；两者同时出现时取更大的有效序号 */
                "Last-Event-ID"?: number;
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events 流 */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
